Ehsan/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings  
from django.conf.urls.static import static 
from router import router 
from rest_framework.authtoken import views as tokenview
from drf_spectacular.views import SpectacularAPIView,SpectacularSwaggerView
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view(),name='index'),
    path('home/',views.HomeView.as_view(),name='home'),
    path('accounts/',include('accounts.urls')),
    path('patients/',include('patients.urls')),
    #API urls
    # path("api/patients",include("patients.api.urls"))
    path('api-token-auth/', views.CustomAuthToken.as_view(), name='api-token-auth'),
    path("api/",include(router.urls)),
    path("api/schema/",SpectacularAPIView.as_view(),name="schema"),
    path("api/schema/docs/",SpectacularSwaggerView.as_view(url_name = "schema")),
    path("firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
        name="firebase-messaging-sw.js"
    ),
    
    
]

if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import CustomLoginView


app_name = 'accounts'
urlpatterns = [
    path('login/',CustomLoginView.as_view(),name="login"),
    path('logout/',LogoutView.as_view(),name="logout"),
]

patients/urls.py
from django.urls import path
from .views import *

app_name = 'patients'

urlpatterns = [
    path('',PatientList.as_view(),name="patient-list"),
    path('patienthistory',PatientHistory.as_view(),name="patient-history-list"),
    path('createpatient/',CreatePatient.as_view(),name="add-patient"),
    path('updatepatient/<int:pk>/',UpdatePatient.as_view(),name="update-patient"),
    path('deletepatient/<int:pk>/',DeletePatient.as_view(),name="delete-patient"),
    path('patientdetail/<int:pk>',PatientDetail.as_view(),name="patient-detail"),
    path('createpatientcase/<pk>',PatientCaseCreate.as_view(),name="create-case"),
    path('casedetail/<int:pk>',PatientCaseDetail.as_view(),name = "case-detail"),
    path('updatepatientcase/<int:pk>/',UpdatePatientCase.as_view(),name="case-update"),
    path('deletepatientcase/<int:pk>/',DeletePatientCase.as_view(),name="delete-case"),
    path("approvecase/<pk>",approve_case,name="approve-case"),
    path("succeedcase/<pk>",succeed_case,name="succeed-case"),
    path("acceptcase/<pk>",accept_case,name="accept-case"),
]   

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://bootswatch.com/5/morph/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://www.gstatic.com/firebasejs/9.14.0/firebase-app-compat.js"></script>
    <script src="https://www.gstatic.com/firebasejs/9.14.0/firebase-messaging-compat.js"></script>
    <title>Ehsan</title>
    {% block links %}

</head>
<body>
      {% if user.hospitalemployee %}
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
      {% else %}
      <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
      {% endif %}
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <img src="{% static 'pics\ahmedrasheed-02.png' %}" alt="Logo" width="50" height="50" class="d-inline-block align-text-top">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            {% if user.is_authenticated %}
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'patients:patient-list' %}">Patients</a>
              <a class="nav-link" href="{% url 'patients:patient-history-list' %}">History</a>
              <a class="nav-link" href="{% url 'patients:add-patient' %}">Add Patient</a>
              <form id="frm_logout" method="post" action="{% url 'accounts:logout' %}">
              {% csrf_token %}
              <input class="nav-link" type="submit" value="logout">
              </form>
              <a class="nav-link">{{ user.username|title }}</a>
            {% endif %}
            </div>
        {% endblock %}

          </div>
        </div>
      </nav>
      <div class="container-fluid">
        {% block content %}

        {% endblock %}
    </div>
<script src="{% static 'js/firebase-messaging.js' %}"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}
    {% if user.hospital %}
    <h1>Welcome {{user.hospital.hospital|title}}</h1>
    {% else %}
    <h1>Welcome {{user.username|title}}</h1>
    {% endif %}
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block links %}
<div class="container">
    <h1>Welcome to Ehsan Donor Managment System</h1>
    <a href="{% url 'accounts:login' %}" class="btn btn-default">Sign in </a>
</div>
{% endblock %}