Ehsan/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings  
from django.conf.urls.static import static 
from router import router 
from rest_framework.authtoken import views as tokenview
from drf_spectacular.views import SpectacularAPIView,SpectacularSwaggerView
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view(),name='index'),
    path('home/',views.HomeView.as_view(),name='home'),
    path('accounts/',include('accounts.urls')),
    path('patients/',include('patients.urls')),
    #API urls
    # path("api/patients",include("patients.api.urls"))
    path('api-token-auth/', views.CustomAuthToken.as_view(), name='api-token-auth'),
    path("api/",include(router.urls)),
    path("api/schema/",SpectacularAPIView.as_view(),name="schema"),
    path("api/schema/docs/",SpectacularSwaggerView.as_view(url_name = "schema")),
    path("firebase-messaging-sw.js",
        TemplateView.as_view(
            template_name="firebase-messaging-sw.js",
            content_type="application/javascript",
        ),
        name="firebase-messaging-sw.js"
    ),
    
    
]

if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

patients/urls.py
from django.urls import path
from .views import *

app_name = 'patients'

urlpatterns = [
    path('',PatientList.as_view(),name="patient-list"),
    path('patienthistory',PatientHistory.as_view(),name="patient-history-list"),
    path('createpatient/',CreatePatient.as_view(),name="add-patient"),
    path('updatepatient/<int:pk>/',UpdatePatient.as_view(),name="update-patient"),
    path('deletepatient/<int:pk>/',DeletePatient.as_view(),name="delete-patient"),
    path('patientdetail/<int:pk>',PatientDetail.as_view(),name="patient-detail"),
    path('createpatientcase/<pk>',PatientCaseCreate.as_view(),name="create-case"),
    path('casedetail/<int:pk>',PatientCaseDetail.as_view(),name = "case-detail"),
    path('updatepatientcase/<int:pk>/',UpdatePatientCase.as_view(),name="case-update"),
    path('deletepatientcase/<int:pk>/',DeletePatientCase.as_view(),name="delete-case"),
    path("approvecase/<pk>",approve_case,name="approve-case"),
    path("succeedcase/<pk>",succeed_case,name="succeed-case"),
    path("acceptcase/<pk>",accept_case,name="accept-case"),
]   

patients/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from accounts.models import Hospital
from django.urls import reverse,reverse_lazy
from django.utils import timezone
from .fcm import send_message
from firebase_admin.messaging import Message, Notification
from fcm_django.models import FCMDevice
from .fcm import send_message
from django.contrib.auth.models import User



# Create your models here.
class Patient(models.Model):
    male = "Male"
    female = "Female"
    Gender_choices = {
        male:"Male",
        female:"Female"
    }
    first_name = models.CharField(max_length = 256)
    middle_name = models.CharField(max_length = 256)
    last_name = models.CharField(max_length = 256)
    phone_number = models.PositiveIntegerField()
    age = models.PositiveSmallIntegerField()
    sex = models.CharField(max_length=6,choices = Gender_choices)
    

    def __str__(self) -> str:
        return "{} {} {}".format(self.first_name,self.middle_name,self.last_name).title()
    
    def get_absolute_url(self):
        return reverse_lazy("patients:create-case",kwargs={'pk':self.pk})


class PatientCase(models.Model):
    urgent = "Urgent"
    surgery ="Surgery"
    treatment = "Treatment"
    case_type_choices = {
        urgent : "Urgent",
        surgery : "Surgery",
        treatment : "Treatment"
    }
    patient_name = models.ForeignKey(Patient,models.CASCADE)
    reported_by = models.ForeignKey(Hospital,on_delete=models.SET_NULL,null=True)
    diagnose = models.CharField(max_length = 256)
    is_successful = models.BooleanField(default = False,verbose_name = "Successful")
    cost = models.PositiveIntegerField()
    case_type = models.CharField(max_length=10,choices = case_type_choices)
    created_date = models.DateTimeField(default = timezone.now)
    is_approve = models.BooleanField(default = False,verbose_name = "Approve") #work on it
    is_accepted = models.BooleanField(default = False,verbose_name = "Accept") #validated
    docs =  models.FileField(upload_to='patients_docs',null=True)

    def __str__(self) -> str:
        return  "{}-{}".format(self.patient_name,self.diagnose).title()
    
    
    def approve(self):
        self.is_approve = True
        self.save()

    def succeeded(self):
        self.is_successful = True
        self.save()
    
    def accepted(self):
        self.is_accepted = True
        self.save()

    class Meta:
        permissions = (("can_approve_cases","Set case as approved"),
                       ("can_succeed_case","Set case as successful"),)
        
        ordering = ["-created_date"]

@receiver(post_save, sender = PatientCase)
def notify_admin_case(sender, instance = None, created = False, **kwargs):
    if created:
        mess = Message(
        notification=Notification(title="New Case", 
                                  body="A new case was added by a hospital check it out!",
                                  image='https://img.freepik.com/free-vector/hospital-building-concept-illustration_114360-8250.jpg?w=1060&t=st=1713138548~exp=1713139148~hmac=efcc95fb70d0f61ef4f10874d38994b404cee5d87e085b7c3df334ae2739d0a7'),
        )
        users = User.objects.filter(systememployee__isnull=False)
        devices = FCMDevice.objects.filter(user__in=users)
        if devices.exists():
                devices.send_message(mess)


@receiver(post_save, sender = PatientCase)
def notify_hospital_case(sender, instance = None, created = False, **kwargs):
    print("approved")
    if instance.is_approve and instance.is_successful == False:
        mess = Message(
        notification=Notification(title="{} case is approved".format(instance.diagnose).title(), 
                                  body="A case has been approved initiate the treatment!",
                                  image='https://img.freepik.com/free-vector/hospital-building-concept-illustration_114360-8250.jpg?w=1060&t=st=1713138548~exp=1713139148~hmac=efcc95fb70d0f61ef4f10874d38994b404cee5d87e085b7c3df334ae2739d0a7'),
        )
        users = User.objects.filter(hospitalemployee__hospital=instance.reported_by)
        devices = FCMDevice.objects.filter(user__in=users)
        if devices.exists():
                devices.send_message(mess)



        
        

        

patients/forms.py
from django import forms
from .models import PatientCase

class PatientCaseForm(forms.ModelForm):
    class Meta:
        model = PatientCase
        fields = ('diagnose','cost','docs','case_type',)

    

patients/api/views.py
from . import serializer
from patients.models import PatientCase
from rest_framework.viewsets import ModelViewSet
from rest_framework.filters import SearchFilter
from django_filters import rest_framework as filters

# class CaseTypeFilter(filters.FilterSet):
#     """
#     A custom filter to filter based on case type
#     no need for this shit it can be implemented in search field
#     """
#     case_type = filters.CharFilter(lookup_expr='iexact')

#     class Meta:
#         model = PatientCase
#         fields = ['case_type']


class PatientCaseViewSet(ModelViewSet):
    serializer_class = serializer.PatientCaseSerializer
    queryset = PatientCase.objects.filter(is_accepted = True,is_approve = False)
    http_method_names = ["get",]
    search_fields = ['diagnose']
    filter_backends = [SearchFilter]
    # filter_backends = [SearchFilter,filters.DjangoFilterBackend]
    # filterset_class = CaseTypeFilter
    # pagination_class = "PageNumberPagination"

patients/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import (ListView,CreateView,UpdateView,DeleteView,DetailView,FormView)
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.contrib.auth import get_user
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from .forms import PatientCaseForm
from accounts.models import HospitalEmployee,Hospital
from patients.models import *
from firebase_admin.messaging import Message,Notification
from fcm_django.models import FCMDevice
from .fcm import send_message
import threading

# Create your views here.
class PatientList(LoginRequiredMixin,ListView):
    model = Patient

    def get_queryset(self) -> QuerySet[Any]:
        querySet = super().get_queryset()
        #query for hospital employee
        try:
            #query for hospital employee
            hospital = self.request.user.hospitalemployee.hospital
            return querySet.filter(patientcase__reported_by = hospital,
                                    patientcase__is_successful = False)
        except:                
            #query for system employee
            try:
                if self.request.user.systememployee:
                    return querySet.filter(patientcase__is_approve = False)
                
            except:
                return super().get_queryset()   
        #context name will be patieint_list

class PatientHistory(LoginRequiredMixin,ListView):
    model = Patient
    template_name_suffix = 'history_list'

    def get_queryset(self) -> QuerySet[Any]:
        queryset = super().get_queryset()
        return queryset.filter(patientcase__is_successful = True)

            
def approve_case(request,pk):
    patient_case = get_object_or_404(PatientCase,pk = pk)
    patient_case.approve()
    patient_pk = patient_case.patient_name.id

    return redirect("patients:patient-detail",pk = patient_pk )

def succeed_case(request,pk):
    patient_case = get_object_or_404(PatientCase,pk = pk)
    patient_case.succeeded()
    patient_pk = patient_case.patient_name.id
    return redirect("patients:patient-detail",pk = patient_pk )

def accept_case(request,pk):
    # thread = threading.Thread(target=send_message)
    # thread.start()
    patient_case = get_object_or_404(PatientCase,pk = pk)
    patient_case.accepted()
    patient_pk = patient_case.patient_name.id 
    # return redirect("patients:patient-detail",pk = patient_pk )
    return redirect("patients:patient-detail",pk = patient_pk )


class CreatePatient(LoginRequiredMixin,CreateView):
    model = Patient
    fields = '__all__'

class UpdatePatient(LoginRequiredMixin,UpdateView):
    model = Patient
    fields = '__all__'
    template_name_suffix = "_update_form"
    # success_url = reverse_lazy('patients:patient-list')

    def get_success_url(self):
        return reverse_lazy('patients:patient-detail',kwargs = {'pk' : self.object.pk})

class DeletePatient(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    model = Patient
    success_url = reverse_lazy('patients:patient-list')
    context_object_name = "patient"
    permission_required = "patients.delete_patient"


class PatientDetail(LoginRequiredMixin,DetailView):
    model = Patient
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        query = PatientCase.objects.filter(patient_name_id = self.kwargs['pk'])
        context['patientcase'] = query
        return context

    #Patient Cases
    
class PatientCaseCreate(LoginRequiredMixin,CreateView):
    model = PatientCase
    form_class = PatientCaseForm
    template_name = 'patients/patientcase_form.html'

    def form_valid(self, form):
        patient = get_object_or_404(Patient, pk=self.kwargs['pk'])
        try:
            hospital = self.request.user.hospitalemployee.hospital    
        except:
            hospital = Hospital.objects.get(hospital_name = 'admin')

        patientcase = form.save(commit=False)
        patientcase.patient_name = patient
        patientcase.reported_by = hospital
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('patients:patient-detail', kwargs={'pk': self.object.patient_name.pk})


class PatientCaseDetail(LoginRequiredMixin,DetailView):
    model = PatientCase
    context_object_name = "patientcase"

class UpdatePatientCase(LoginRequiredMixin,UpdateView):
    model = PatientCase
    fields = ('diagnose','cost','case_type')
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse_lazy("patients:case-detail",kwargs = {'pk':self.object.pk})
    

class DeletePatientCase(LoginRequiredMixin,PermissionRequiredMixin,DeleteView):
    model = PatientCase
    context_object_name = "patientcase"
    permission_required = "patients.delete_patientcase"
    

    def get_success_url(self) -> str:
        return reverse_lazy("patients:patient-detail",kwargs = {'pk':self.object.patient_name.pk})
    

patients/templates/patients/patient_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="container-fluid">Deleting Patient</h1>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ patient }}</p>
    <input class="btn btn-danger" type="submit" value="Delete">
    <a href="{% url 'patients:patient-list' %}" class="btn btn-default">cancel</a>
</form>
{% endblock %}

patients/templates/patients/patient_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <h1>Enter the patients data</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Save" class="btn btn-default">
    </form>
</div>
{% endblock %}

patients/templates/patients/patient_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<h1 class="container-fluid">Patients List</h1>

<table class="table container-fluid">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Sex</th>
        <th scope="col">Options</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in patient_list %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td> <a href="{% url 'patients:patient-detail' patient.id %}">{{ patient.first_name|title }} {{ patient.middle_name|title }} {{ patient.last_name|title }} </a></td>
        <td>{{ patient.age }}</td>
        <td>{{ patient.sex }}</td>
        <td>
          {% if perms.patients.change_patient %}
          <a href="{% url 'patients:update-patient' patient.id %}" class="btn btn-warning btn-sm">Update</a>
          {% endif %}

          {% if perms.patients.delete_patient %}
          <a href="{% url 'patients:delete-patient' patient.id%}" class="btn btn-danger btn-sm">Delete</a>
          {% endif %}

        </td>

        <td>
          {% with patient.patientcase_set.all|first as case %}
          {% if case.is_successful == True and case.is_accepted == True and case.is_approve == True %}
          <span class="badge rounded-pill bg-success">Success</span>
          {% elif case.is_accepted == True and case.is_approve == True %}
          <span class="badge rounded-pill bg-warning">Work on it</span>
          {% elif case.is_accepted == True %}
          <span class="badge rounded-pill bg-primary">In The system</span>
          {% else %}
          <span class="badge bg-danger">Pending</span>
          {% endif %}
          {% endwith %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

patients/templates/patients/patient_update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-default" value="Update">
        </form>
    </div>
{% endblock %}

patients/templates/patients/patientcase_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<h1 class="container-fluid">Deleting Patient Case</h1>
    <div class="container-fluid">
        <form method="post">
            {% csrf_token %}
            <p>Are you sure you want to delete {{ patientcase|title }}'s case</p>
            <input type="submit" class="btn btn-default" value="Delete">
        </form>
    </div>
{% endblock %}

patients/templates/patients/patientcase_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save" class="btn btn-default">   
</form>
{% endblock %}

patients/templates/patients/patientcase_update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container-fluid">
    <h1>Patient Case Update</h1>
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-default" value="Update">
        </form>
    </div>
{% endblock %}

patients/templates/patients/patienthistory_list.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<head>
  <style>
      td {
          font-weight: bold;
      }
      a{
        text-decoration: none;
      }
  </style>
</head>

<h1 class="container-fluid">Patients List</h1>

<table class="table container-fluid">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Age</th>
        <th scope="col">Sex</th>
        <th scope="col">Options</th>
        <th scope="col">Status</th>
      </tr>
    </thead>
    <tbody>
      {% for patient in patient_list %}
      <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td> <a href="{% url 'patients:patient-detail' patient.id %}">{{ patient.first_name|title }} {{ patient.middle_name|title }} {{ patient.last_name|title }} </a></td>
        <td>{{ patient.age }}</td>
        <td>{{ patient.sex }}</td>
        <td>
          {% if perms.patients.change_patient %}
          <a href="{% url 'patients:update-patient' patient.id %}" class="btn btn-warning btn-sm">Update</a>
          {% endif %}
        </td>

        <td>
          {% with patient.patientcase_set.all|first as case %}
          <span class="badge rounded-pill bg-success">Success</span>
          {% endwith %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}